name: Deploy Project
on: [push] 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code #get the code, since jobs run on a github server, which does not have our code
        uses: actions/checkout@v3 #when you want to use an action
      - name: Install NodeJS
        uses: actions/setup-node@v3 #we need node-js for running the test, so we install it here
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Lint
        run: npm run lint
      - name: Build code
        run: npm run build